#! /bin/sh

# Set the number of workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Launch keybindings daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Window configurations
bspc config border_width         0
bspc config window_gap           8
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Padding outside of the window
bspc config top_padding            8
bspc config bottom_padding         8
bspc config left_padding           8
bspc config right_padding          8

# Move floating windows
bspc config pointer_action1 move

# Resize floating windows
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# Set background and top bar
systemctl --user start polybar
