#! /bin/sh

# Set the number of workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Launch the keybindings daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Launch the top bar
polybar &> /dev/null

# Configurations
bspc config border_width         2
bspc config window_gap           15
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding            4
bspc config bottom_padding         4
bspc config left_padding           4
bspc config right_padding          4

bspc config pointer_action1 move
bspc config pointer_follows_focus	true
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
